#!/bin/bash

function removemenu() {
  xdg-desktop-menu uninstall --mode system epidata-epidata.directory epidata-epidataentryclient.desktop
}

case $1 in
  remove) ;;
  upgade)
    removemenu;;
  remove)
    removemenu;;
  deconfigure) ;;
  failed-upgrade) ;;
  *) ;;
esac



