name: Build Analysis Artifact

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  setup:
    name: Building Linux Installers
    runs-on: ubuntu-latest
    container:
      image: epidata/fpcbuild:3.2.0-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          output_file: "/etc/maven/settings.xml"
          servers:
            '[{
            "id": "github",
            "username": "${{ secrets.CI_USER }}",
            "password": "${{ secrets.CI_PASSWORD }}"
            }]'
          repositories:
            '[
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/epidata-dk/parent/",
                "snapshots": {
                  "enabled": "true"
                }                
              }
            ]'

      - name: Resolve versions
        run: mvn versions:resolve-ranges

      - name: Pull dependencies
        run: mvn validate -U

      - name: Build All
        run: ./build_all.sh

      # - name: SFTP Deploy
      #   uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      #   with:
      #       username: ${{ secrets.SFTP_USER }}
      #       password: ${{ secrets.SFTP_PASSWORD }} 
      #       server: ${{ secrets.SFTP_SERVER }}
      #       local_path: 'target/output/*'
      #       remote_path: '${{ secrets.SFTP_REMOTE_PATH }}'
      #       sftp_only: true


