name: Build EpiData Release Artifacts

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  linux:
    name: Building Linux Installers
    runs-on: ubuntu-latest
    container:
      image: epidata/release-builder:0.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          output_file: "/usr/share/java/maven-3/conf/settings.xml"
          servers:
            '[{
            "id": "github",
            "username": "${{ secrets.CI_USER }}",
            "password": "${{ secrets.CI_PASSWORD }}"
            }]'
          repositories:
            '[
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/epidata-dk/parent/",
                "snapshots": {
                  "enabled": "true"
                }                
              }
            ]'

      - name: Resolve versions
        run: mvn versions:resolve-ranges

      - name: Pull dependencies
        run: mvn validate -U

      - name: Build All
        run: ./build.sh linux

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-releases
          path: |
            target/output/epidata*.linux.tgz
            target/output/epidata*.deb


  mac:
    name: Building Darwin Installers
    runs-on: ubuntu-latest
    container:
      image: epidata/release-builder:0.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          output_file: "/usr/share/java/maven-3/conf/settings.xml"
          servers:
            '[{
            "id": "github",
            "username": "${{ secrets.CI_USER }}",
            "password": "${{ secrets.CI_PASSWORD }}"
            }]'
          repositories:
            '[
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/epidata-dk/parent/",
                "snapshots": {
                  "enabled": "true"
                }                
              }
            ]'

      - name: Resolve versions
        run: mvn versions:resolve-ranges

      - name: Pull dependencies
        run: mvn validate -U

      - name: Build All
        run: ./build.sh darwin

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: darwin-releases
          path: |
            target/output/epidata*.darwin.zip
            target/output/epidata*.dmg


  windows:
    name: Building Windows Installers
    runs-on: ubuntu-latest
    container:
      image: epidata/release-builder-win:1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          output_file: "/etc/maven/settings.xml"
          servers:
            '[{
            "id": "github",
            "username": "${{ secrets.CI_USER }}",
            "password": "${{ secrets.CI_PASSWORD }}"
            }]'
          repositories:
            '[
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/epidata-dk/parent/",
                "snapshots": {
                  "enabled": "true"
                }                
              }
            ]'

      - name: Resolve versions
        run: mvn versions:resolve-ranges

      - name: Pull dependencies
        run: mvn validate -U

      - name: Build All
        run: ./build.sh windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-releases
          path: |
            target/output/epidata*.win64.zip
            target/output/epidata*.exe


